SKIP UPGRADE TEST init commit
terraform-ibm-modules/terraform-ibm-secrets-manager pull request #1
Opened 2023-11-27 14:30 UTC by Khuzaima05

### Description

Migrating secrets-manager to public

issue: https://github.ibm.com/GoldenEye/issues/issues/6572

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-11-27 14:30 UTC, Khuzaima05 commented
/run pipeline

2023-11-28 12:20 UTC, shemau requested changes
This looks good to me. An existing issue with using github rather than registry for a module.

2023-11-28 12:47 UTC, ocofaigh commented on README.md
> +  version                              = "X.X.X"  # Replace "X.X.X" with a release version to lock into a specific release
can you fix the indentation here so all equal signs are aligned?

2023-11-28 12:48 UTC, ocofaigh commented on examples/basic/variables.tf
> +  description = "The IBM Cloud API token this account authenticates to"
its not a token, its an API key

2023-11-28 12:49 UTC, ocofaigh commented on examples/complete-private/README.md
> +<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
remove the tf docs content from example

2023-11-28 12:51 UTC, ocofaigh commented on examples/complete/variables.tf
> +  description = "Secrets-Manager Trial plan"
Update this description to: The Secrets Manager service plan to provision

2023-11-28 12:52 UTC, ocofaigh commented on examples/complete/version.tf
> +    # Pin to the lowest provider version of the range defined in the main module to ensure lowest version still works
remove this comment, it is not accurate - its not pinned to lowest

2023-11-28 12:53 UTC, ocofaigh requested changes
I left a few minor comments

2023-11-29 09:26 UTC, Khuzaima05 commented on examples/complete-private/main.tf
> +  source = "git::https://github.com/terraform-ibm-modules/terraform-ibm-resource-group.git?ref=v1.1.4"
Done

2023-11-29 09:53 UTC, Khuzaima05 commented
/run pipeline

2023-11-29 14:28 UTC, shemau approved these changes
Approved. All comments from myself and Conall resolved.

2023-11-29 16:37 UTC, ocofaigh approved these changes

2023-11-29 16:37 UTC, merged

2023-11-29 16:38 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: