feat: add support to use existing SM instance for DA
terraform-ibm-modules/terraform-ibm-secrets-manager pull request #109
Opened 2024-04-25 15:16 UTC by akocbek

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-26 09:38 UTC, akocbek commented
/run pipeline

2024-04-26 11:05 UTC, akocbek commented
/run pipeline

2024-04-26 13:43 UTC, akocbek commented
/run pipeline

2024-04-26 14:49 UTC, akocbek commented
/run pipeline

2024-04-26 15:19 UTC, akocbek commented
```

 2024/04/26 15:02:49 Terraform apply | Error: [ERROR] Error when creating resource instance: Please contact the Service Provider for this error. [422, Unprocessable Entity] This account reached the number of Trial plan instances that are allowed. To proceed, you must select the Standard plan or delete an existing Trial instance. If you delete the Trial plan instance, you must also delete its reclamation by using the IBM Cloud CLI. Learn more: https://ibm.biz/BdPa49 with resp code: {
 ``` 
region: eu-de

2024-04-26 15:19 UTC, akocbek commented
/run pipeline

2024-04-26 15:51 UTC, akocbek commented
/run pipeline

2024-04-26 17:00 UTC, vburckhardt commented
@ocofaigh - is there a need to clean up trial instances?

2024-04-26 17:07 UTC, akocbek commented
/run pipeline

2024-04-26 19:15 UTC, ocofaigh commented on solutions/standard/variables.tf
> +  description = "The CRN of an existing KMS key to use for Secrets Manager. If not supplied, a new key ring and key will be created."
The description is wrong here.

2024-04-26 19:15 UTC, ocofaigh requested changes
just 1 comment

2024-04-29 06:59 UTC, akocbek commented
/run pipeline

2024-04-29 07:41 UTC, ocofaigh approved these changes

2024-04-29 07:47 UTC, merged