Update variables.tf
terraform-ibm-modules/terraform-ibm-secrets-manager pull request #141
Opened 2024-06-12 16:14 UTC by joealewine

### Description

Update variables.tf for Core Security Services DA.

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-06-12 18:35 UTC, alex-reiff commented on solutions/standard/variables.tf
> +  description = "Set this to true to configure an Secrets Manager public certificate engine for an existing Secrets Manager instance. If set to false, no public certificate engine will be configured
an Secrets Manager -> a

2024-06-12 18:37 UTC, alex-reiff commented on solutions/standard/variables.tf
> +  description = "The CRN of an existing Key Protect key to use for Secrets Manager. If not supplied, a new key ring and key will be created."
can also be a Hyper Protect Crypto Services key

2024-06-12 19:43 UTC, SirSpidey requested changes
Joe, suggestions from other DAs and from guidance I've come up with. Let me know if you have concerns with any of these.

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The name of a new or an existing resource group where the Secrets Manager resources are provisioned. If prefix input variable is passed then it is prefixed in front of the value in t
```suggestion
  description = "The name of a new or existing resource group to provision resources to. If a prefix input variable is passed, it is added to the value in the `<prefix>-value` format. Optional if `existing_secrets_manager_crn` is not specified."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The region where Secrets Manager resources are provisioned."
```suggestion
  description = "The region to provision resources to."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "An optional prefix to append to all resources created by this solution."
```suggestion
  description = "The prefix to apply to all resources created by this solution."
```

Trying to remove the optional label. It's clear in the Cloud UI.

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The name to give the Secrets Manager instance provisioned by this solution. If the prefix input variable is passed then it is prefixed infront of the value in the format of '<prefix>
```suggestion
  description = "The name to give the Secrets Manager instance provisioned by this solution. If a prefix input variable is specified, it is added to the value in the `<prefix>-value` format."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +    error_message = "Only \"public\" and \"private\" are allowed values for 'existing_secrets_endpoint_type'."
We want to add the information to the description before they get the error (line 53)

description = "The endpoint type to use if `existing_secrets_manager_crn` is specified. Possible values: `public`, `private`."

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The pricing plan to use when provisioning a new Secrets Manager instance. Only 'standard' and 'trial' are allowed values. This variable is only used if `provision_sm_instance` is set
```suggestion
  description = "The pricing plan to use when provisioning a Secrets Manager instance. Possible values: `standard`, `trial`. Applies only if `provision_sm_instance` is set to `true`."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The types of service endpoints to set on the Secrets Manager instance. Only `private-only` or `public-and-private` are allowed."
```suggestion
  description = "The types of service endpoints to set on the Secrets Manager instance. Possible values: `private-only`, `public-and-private`."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The name of the DNS provider for the public_cert secrets engine."
```suggestion
  description = "The name of the DNS provider for the public certificate secrets engine configuration."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The CRN of an existing Key Protect key to use for Secrets Manager. If not supplied, a new key ring and key will be created."
```suggestion
  description = "The CRN of a Key Protect or Hyper Protect Crypto Services key to use for Secrets Manager. If not specified, a key ring and key are created."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The CRN of the existing Hyper Protect Crypto Services or Key Protect instance. This is only required if not supplying an existing key to use for Secrets Manager."
```suggestion
  description = "The CRN of the Hyper Protect Crypto Services or Key Protect instance. Applies only if `existing_secrets_manager_kms_key_crn` is not specified."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The type of endpoint to be used for communicating with the Key Protect or Hyper Protect Crypto Services instance. Both 'public' or 'private' are allowed. This value is only required
```suggestion
  description = "The type of endpoint to use for communicating with the Key Protect or Hyper Protect Crypto Services instance. Possible values: `public`, `private`. Applies only if `existing_secrets_manager_kms_key_crn` is not specified."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The name to give to the new key ring used to store the key. Only required if not supplying an existing root key CRN. If the prefix input variable is passed it is added in the format
```suggestion
  description = "The name for the new key ring to store the key. Applies only if `existing_secrets_manager_kms_key_crn` is not specified. If a prefix input variable is passed, it is added to the value in the `<prefix>-value` format. ."
```

2024-06-12 19:43 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The name to give to the new root key. Only required if not supplying an existing root key CRN. If the prefix input variable is passed it is added in the format of '<prefix>-value'."
```suggestion
  description = "The name for the new root key. Applies only if `existing_secrets_manager_kms_key_crn` is not specified. If a prefix input variable is passed, it is added to the value in the `<prefix>-value` format."
```

2024-06-13 13:06 UTC, joealewine commented
Thanks @alex-reiff and @SirSpidey for the great comments. I've either addressed or accepted them all.

2024-06-14 15:58 UTC, SirSpidey requested changes
@joealewine a few open suggestions

2024-06-14 15:58 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The pricing plan to use when provisioning a new Secrets Manager instance. Only 'standard' and 'trial' are allowed values. This variable is only used if `provision_sm_instance` is set
open suggestion

2024-06-14 15:58 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The types of service endpoints to set on the Secrets Manager instance. Only `private-only` or `public-and-private` are allowed."
open suggestion

2024-06-14 15:58 UTC, SirSpidey commented on solutions/standard/variables.tf
> +  description = "The name of the DNS provider for the public_cert secrets engine."
open suggestion

2024-06-14 16:09 UTC, SirSpidey approved these changes
👍

2024-06-14 16:09 UTC, SirSpidey commented
/run pipeline

2024-06-14 21:26 UTC, MatthewLemmond commented
/run pipeline

2024-06-15 13:23 UTC, merged