fix: remove endpoint variables
terraform-ibm-modules/terraform-ibm-secrets-manager pull request #225
Opened 2024-11-05 16:19 UTC by MatthewLemmond

### Description
Remove the endpoint variables from the module calls to Secrets Manager and KMS modules and hard-code the value in the call to be private in order to follow a secure-by-default approach without allowing changes to this.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Removed `existing_secrets_endpoint_type`, `allowed_network`, and `kms_endpoint_type` to require these values always be pointing to private endpoints/network

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-11-05 16:20 UTC, alex-reiff approved these changes

2024-11-05 16:25 UTC, MatthewLemmond commented
/run pipeline

2024-11-05 16:29 UTC, MatthewLemmond commented
/run pipeline

2024-11-05 16:32 UTC, shemau requested changes
Looks good to me. Requires that DA uses private endpoints for SM.

But, DA has properties in ./ibm_catalog.json that will require update (removal). Which raises the issue of migration for any customer who has already deployed with public.

2024-11-05 17:12 UTC, ocofaigh reviewed
The upgrade test will no longer work with this change until we have support to run upgrade test in schematics (which is another week or two out).
One thing we could do is hide them in the `ibm_catalog.json` so catalog consumers cant use them, but we can still use them in the code. And then when we have schematics upgrade test support, we can fully remove them?

2025-04-15 11:34 UTC, shemau commented
This PR is no longer required, since it was implemented elsewhere. A check against main branch today shows that this code is in the `security-enforced` DA and is not in the `fully-configurable DA` which is as expected.

2025-04-15 11:34 UTC, closed without merging