feature: iam engine option
terraform-ibm-modules/terraform-ibm-secrets-manager pull request #89
Opened 2024-04-08 16:32 UTC by jor2

### Description

Expose ability to configure IAM engine in SM instance in DA

https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/77

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-08 16:33 UTC, jor2 commented
/run pipeline

2024-04-08 18:37 UTC, jor2 commented
/run pipeline

2024-04-09 12:59 UTC, jor2 commented
/run pipeline

2024-04-09 13:21 UTC, jor2 commented
/run pipeline

2024-04-09 13:21 UTC, jor2 commented
/run pipeline

2024-04-09 14:54 UTC, jor2 commented
/run pipeline

2024-04-09 15:06 UTC, ocofaigh requested changes
see comments - also diagram for DA will need to be updated to show IAM engine

2024-04-09 15:06 UTC, ocofaigh commented on solutions/standard/variables.tf
> +  description = "Set this to true to to configure an IBM Secrets Manager IAM credentials engine for an existing IBM Secrets Manager instance. If set to false, no iam engine will be configured for you
Maybe don't say `for an existing IBM Secrets Manager instance` - the instance is provisioned as part of the DA solution

2024-04-09 15:06 UTC, ocofaigh commented on solutions/standard/main.tf
> +  validate_iam_secrets_engine = var.iam_engine_enabled && var.iam_engine_name == null ? tobool("When setting var.iam_engine_enabled to true, a value must be passed for var.iam_engine_name") : true
hmm, not really needed since `iam_engine_name` has a default value.

2024-04-09 15:06 UTC, ocofaigh commented on tests/pr_test.go
> +		{Name: "prefix", Value: options.Prefix, DataType: "string"},
There is no prefix variable for the DA

2024-04-09 17:45 UTC, jor2 commented
/run pipeline

2024-04-09 18:58 UTC, ocofaigh commented
@jor2 I think there is a bug in the secrets group module that needs to be fixed first -> https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-secret-group/issues/148

2024-04-10 16:40 UTC, jor2 commented
/run pipeline

2024-04-10 16:50 UTC, jor2 commented
/run pipeline

2024-04-10 16:51 UTC, jor2 commented
/run pipeline

2024-04-10 17:13 UTC, jor2 commented
still getting
````
 2024/04/10 17:10:57 Terraform apply | Error: CreateSecretGroupWithContext failed Post "https://e9465a83-5a63-4fa9-834e-ba7a86c999e9.us-south.secrets-manager.appdomain.cloud/api/v2/secret_groups": dial tcp: lookup e9465a83-5a63-4fa9-834e-ba7a86c999e9.us-south.secrets-manager.appdomain.cloud on 172.21.0.10:53: no such host
 2024/04/10 17:10:57 Terraform apply | null
 2024/04/10 17:10:57 Terraform apply | 
 2024/04/10 17:10:57 Terraform apply | 
 2024/04/10 17:10:57 Terraform apply |   with module.iam_secrets_engine[0].module.secrets_manager_group_acct[0].ibm_sm_secret_group.secret_group,
 2024/04/10 17:10:57 Terraform apply |   on .terraform/modules/iam_secrets_engine.secrets_manager_group_acct/main.tf line 8, in resource "ibm_sm_secret_group" "secret_group":
 2024/04/10 17:10:57 Terraform apply |    8: resource "ibm_sm_secret_group" "secret_group" {
````

2024-04-10 21:01 UTC, jor2 commented
/run pipeline

2024-04-10 23:04 UTC, jor2 commented
/run pipeline

2024-04-11 12:55 UTC, jor2 commented
> see comments - also diagram for DA will need to be updated to show IAM engine

Updated the diagram, not entirely sure how I should have shown IAM engine.

2024-04-11 12:57 UTC, jor2 commented
/run pipeline

2024-04-11 17:13 UTC, merged

2024-04-11 17:14 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.6.0)
- `v1.6.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: